name: synkhub-api-development
services:
  synkhub-api-development-rails:
    container_name: synkhub-api-development-rails
    image: synkhub-api-development-rails:latest
    build:
      context: ../../.
      dockerfile: docker/Dockerfile
      target: synkhub-api-development-image
    entrypoint: /app/docker/entrypoint.sh
    command: bundle exec puma -C config/puma.rb
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - ../../.:/app
      - synkhub-api-development-bundle-cache:/usr/local/bundle
    depends_on:
      synkhub-api-development-postgresql:
        condition: service_healthy
      synkhub-api-development-redis:
        condition: service_started
    ports:
      - 3000:3000
    env_file: ../../.env
    networks:
      - synkhub-api-development-network

  synkhub-api-development-sidekiq:
    container_name: synkhub-api-development-sidekiq
    image: synkhub-api-development-rails:latest
    command: bundle exec sidekiq -C config/sidekiq.yml
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - ../../.:/app
      - synkhub-api-development-bundle-cache:/usr/local/bundle
    depends_on:
      synkhub-api-development-postgresql:
        condition: service_healthy
      synkhub-api-development-redis:
        condition: service_started
    env_file: ../../.env
    networks:
      - synkhub-api-development-network

  synkhub-api-development-postgresql:
    container_name: synkhub-api-development-postgresql
    image: postgres:16-alpine
    user: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - synkhub-api-development-postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - synkhub-api-development-network

  synkhub-api-development-redis:
    container_name: synkhub-api-development-redis
    image: redis:7-alpine
    volumes:
      - synkhub-api-development-redis-data:/data
    networks:
      - synkhub-api-development-network

networks:
  synkhub-api-development-network:
    name: synkhub-api-development-network

volumes:
  synkhub-api-development-bundle-cache:
  synkhub-api-development-postgresql-data:
  synkhub-api-development-redis-data:
